front(ux): travar seleção de período
unb-mds/2023-2-SuaGradeUnB pull request #195
Opened 2024-01-08 19:05 UTC by caio-felipee

**Issue:**
close #189 

**O que foi feito?**
- Quando o usuário já fez seleção de alguma matéria, selecionar o período/ano automaticamente para as próximas matérias.
- Ao fechar a tela de busca, também realiza a limpeza da lista de matérias pesquisadas anteriormente.

2024-01-08 22:14 UTC, mateusvrs requested changes

2024-01-08 22:14 UTC, mateusvrs commented on web/app/components/AsideSchedulePopUp/Form/DisciplineOptionForm.tsx
> +    }, []);
Observe que a adição da lista de dependências necessita de adicionar algumas variáveis e estados externos, ou não deve-se utiliza-la. Poderia verificar isso?

Referência: [useEffect](https://react.dev/reference/react/useEffect#examples-dependencies)

2024-01-12 17:56 UTC, mateusvrs requested changes

2024-01-12 17:56 UTC, mateusvrs commented on web/app/components/AsideSchedulePopUp/Form/DisciplineOptionForm.tsx
> +    }, [disableDefault]);
Boa mudança @caio-felipee, entretanto, percebe-se que há mais alguns estados que foram declarados fora do `useEffect` e que não foram colocados na lista de dependências tais como o `formData`. Recomendo você instalar alguma extensão do VSCode para React.js que indica quais estão faltando assim como eu tenho, observe o aviso:

![image](https://github.com/unb-mds/2023-2-SuaGradeUnB/assets/68292695/5b514508-a6dc-4b0c-a452-7fda2a7c3764)

Eu utilizo as seguintes:
![image](https://github.com/unb-mds/2023-2-SuaGradeUnB/assets/68292695/03e2a5ce-12f3-41bb-8d32-aab0669ffbf0)

2024-01-15 23:33 UTC, caio-felipee commented on web/app/components/AsideSchedulePopUp/Form/DisciplineOptionForm.tsx
> +    }, [disableDefault]);
Boa noite, @mateusvrs. Agradeço pelas observações e recomendações de extensões!

Apenas uma observação (para caso outro alguém leia e ache útil): a extensão que reportou o problema é o *ESLint*.

2024-01-15 23:35 UTC, caio-felipee commented
@mateusvrs peço que revise o código novamente. Os erros reportados foram corrigidos e, uma vez que alterei o método de limpeza de disciplinas pesquisadas, outros podem aparecer.

Desde já, agradeço pela ajuda e revisão!

2024-01-22 00:54 UTC, mateusvrs approved these changes
:smiley:

2024-01-23 14:39 UTC, merged